angiBaseURL: http://www.angi.ru
#angiNewsPath: http://angi.ru/section/90886-%D0%9D%D0%B5%D1%84%D1%82%D1%8C-%D0%B8-%D0%B3%D0%B0%D0%B7/
angiNewsPath: http://angi.ru/section/all-%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8/

excelPathRoot: src/main/resources/generated/


angiExcelFilename: angi_news.xlsx
angiEmailSubject: ANGI news
angiEmailContent: ANGI - From rusiashka with love ;)
angiExcelSheetName: Angi News
angiFilterKeywords: Роснефт, Лукойл, Газпром нефт, Башнефт, Новатэк, Татнефт, Сибур, КазМунайГаз, Сокар, Александр Новак, Цена нефт

ngvBaseURL: http://www.ngv.ru
ngvNewsPath: http://www.ngv.ru/news/
ngvExcelFilename: nvg_news.xlsx
ngvEmailSubject: NGV news
ngvEmailContent: From rusiashka with love ;)
dateFromParam: DATE_ACTIVE_FROM
dateToParam: DATE_ACTIVE_TO
paramQ: q
ngvExcelSheetName: NGV News
